### ISSUE TITLE
Component: Hero (informs DS)

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#7]
The hero component designed by Adam is planned to be used on the cannabis.ca.gov site.

## User needs:
- The cannabis site should have an engaging hero section that showcases the most important content
- This component should be easily edited or swapped out in the WordPress editing environment
- This should be based on the reusable design system element 
- The implementation should be lightweight and fully accessible

## Requirements:
- Create a hero component that matches Adam's designs.
- This component should be installable independently. 
- It should inherit the appropriate parent styles but contain enough code to work on its own. 
- Use only the minimal amount of code to ship this tool. This component probably does not require javascript so it should be created with HTML and CSS only. 
- Component should work smoothly with screenreaders
- Component should be as lightweight as possible not dragging down page performance
- Component should be independently responsive without media queries so that this element can be use appropriate layouts inside any size parent container, not just the entire page 
- Create additional tools to make sure that this component can be used easily inside WordPress and that it will faithfully output the desired styles and markup in that environment.

## Tasks:
- Create the HTML, CSS for the component 
- Get design signoff from Adam on standalone component
- Publish the component as part of the component collection in the design system repository
- Create a custom gutenberg block so that this component can be added to the cannabis.ca.gov WordPress site
- Validate all the WP block functionality with Adam, Michael, and the cannabis content maintainers
- Review the component code generated in WordPress for accessibility, performance
- Review the component custom block authoring experience for accessibility

Screenshots from [figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=436%3A0)

<img width="418" alt="Screen Shot 2021-05-06 at 4 51 31 PM" src="https://user-images.githubusercontent.com/353360/117378994-639f3f00-ae8b-11eb-86f0-bdcc5aeb5464.png">

**Comment by aaronhans** [comment]
Frontend component
- [ ] Use framework free CSS for layout
- [ ] Identify where to inherit CSS variable styles
- [ ] Provide usable defaults for all css variables for older browsers
- [ ] Review in all supported browsers
- [ ] Review output in progressively non-enhanced states like no javascript, no CSS variable support
- [ ] Identify and apply appropriate schema.org microdata format
- [ ] Performance review
- [ ] Automated accessibility review using lighthouse/axe
- [ ] Manual accessibility review for keyboard navigability, screenreader accessibility
- [ ] Component documentation should include design assets, instructions to use, example HTML

Create custom Gutenberg block 
- [ ] Allows insertion of header image leveraging WordPress asset library
- [ ] Editable header element
- [ ] Editable body copy
- [ ] Editable and linkable button
- [ ] Block outputs markup as close as possible to raw component
- [ ] Block contains all extra styles and logic required to render final design while in editing mode
- [ ] User research authoring using this custom block
- [ ] Documentation for custom block should link to component in design system, callout expected external vars

Should split into separate task:
- What icons should we be using for our custom blocks?
- How should we organize our custom blocks, should we have our own category?
- Do we want to hide any of the default blocks WordPress presents?

Need external help with:
- Analytics strategy: Are additional custom events desired? (insights team)
- Content design recommendations: Where should these docs go? (Michael)
- Design review should occur when installed in production environment. Can occur once prod is all setup so we can integrate component and Adam returns

**Comment by aaronhans** [comment]
Integration tasks split into: https://github.com/cagov/cannabis.ca.gov/issues/80

**Comment by m-sullivan7** [comment]
On the content design piece, thanks for asking! I recommend we create a space in our external handbook. Based on what I read here, my impression is that this is the kind of thing we want to share as part of a design system (like the examples we looked at a few weeks ago in Adam's guided exercise). I see the [external handbook](https://handbook.digital.ca.gov/) as the alpha version of that documentation.

I recommend that we revisit our scrappy SpaceBook solution once we're past the cannabis launch.

**Comment by aaronhans** [comment]
Researched micro data options from schema.org. If the hero contains data about an event there is a great structure but if not we would need to choose another category. This category switching and the associated set of fields changing makes adding structured data to this type of element difficult so going to postpone that to a separate ticket.

Looking at the schemas implemented by the UK here: https://docs.publishing.service.gov.uk/manual/schemas.html we should use all those as well as event

**Comment by aaronhans** [comment]
PR for docs: https://github.com/cagov/ca-design-system-gutenberg-blocks/pull/11
